// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAooJDcBNsuyGpa2Dlrc4Lbydl6o40IRTA',
    appId: '1:439057201618:web:b21153509011e4913c700b',
    messagingSenderId: '439057201618',
    projectId: 'travel-app-1ceec',
    authDomain: 'travel-app-1ceec.firebaseapp.com',
    storageBucket: 'travel-app-1ceec.appspot.com',
    measurementId: 'G-4V7KBR2FT6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBUhDrsNmLCUQwftWUHuk2Jz-wNoUS49FI',
    appId: '1:439057201618:android:08a233c2e5b91eee3c700b',
    messagingSenderId: '439057201618',
    projectId: 'travel-app-1ceec',
    storageBucket: 'travel-app-1ceec.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAfGKPgau2go-wTEPbo6FcHjfLJn6z2Fqo',
    appId: '1:439057201618:ios:3fa90494d3bbad453c700b',
    messagingSenderId: '439057201618',
    projectId: 'travel-app-1ceec',
    storageBucket: 'travel-app-1ceec.appspot.com',
    iosBundleId: 'com.example.travelApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAfGKPgau2go-wTEPbo6FcHjfLJn6z2Fqo',
    appId: '1:439057201618:ios:3fa90494d3bbad453c700b',
    messagingSenderId: '439057201618',
    projectId: 'travel-app-1ceec',
    storageBucket: 'travel-app-1ceec.appspot.com',
    iosBundleId: 'com.example.travelApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAooJDcBNsuyGpa2Dlrc4Lbydl6o40IRTA',
    appId: '1:439057201618:web:aaea0dcb0f8a6b6f3c700b',
    messagingSenderId: '439057201618',
    projectId: 'travel-app-1ceec',
    authDomain: 'travel-app-1ceec.firebaseapp.com',
    storageBucket: 'travel-app-1ceec.appspot.com',
    measurementId: 'G-23PDQ586ME',
  );

}